[preference]
# 数据库类型，目前只支持mysql
databasetype = 'mysql'
# 默认分割法
delimiterraw = ';'
# 重定义分隔符
delimitercmd = 'DELIMITER'

# 注释部分，只做字符串查找，不做语法分析，所以不能有效处理字符串转义。
# 单多行注释
linecomment = '--'
# 多行注释，必须成对出现
multcomment = ['/*','*/']

# 日期格式化
fmtdatetime = '2006-01-02 15:04:05.000'

# 控制端口号。负数和零关闭此功能，端口号建议(1024-65535)
# 注意程序启动时，会输出远程连接的控制密码。
# 当通过 127.0.0.* 连接时，可以不输入密码
controlport = 59062

# 连接池有关的，sql.DB一致
connmaxopen = 10
connmaxidel = 2

[sqltemplet]
# 模板在`godbart.toml`中的`sqltemplet`里配置，`key`就是`-t` 参数，多个时用`,`分割。
# 模板使用的`变量`全都存在时，输出模板，全都不存在时不输出，其他则报错。
#
# 系统内置了以下`变量`，不想使用`${}`不可以省略。
#
#  * ${TABLE_NAME}   string, 当前table名
#  * ${TABLE_DDL}    string, 当前table的DDL
#  * ${TRIGGER_NAME} []string, 当前table的trigger名
#  * ${TRIGGER_DDL}  []string, 当前table的trigger的DDL
#  * ${COLUMNS_BASE} string, 当前table的所有列的基本信息(名字和类型)。
#  * ${COLUMNS_FULL} string, 当前table的所有列的全部信息(同创建时，创建DDL必须一行一列，否则解析可能错误)。

tbl='''
DROP TABLE IF EXISTS `${TABLE_NAME}`;
${TABLE_DDL};
'''

trg='''
DROP TRIGGER IF EXISTS `${TRIGGER_NAME}`;
DELIMITER $$
${TRIGGER_DDL} $$
DELIMITER ;
'''

log='''
DROP TABLE IF EXISTS `${TABLE_NAME}$log` ;
-- CREATE TABLE `${TABLE_NAME}$log` AS SELECT * FROM `${TABLE_NAME}` WHERE 1=0;

CREATE TABLE `${TABLE_NAME}$log` (
  ${COLUMNS_FULL},
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `_du` int(11) DEFAULT NULL,
  `_dt` datetime DEFAULT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TRIGGER IF EXISTS `${TABLE_NAME}$log$bu`;
DELIMITER $$
CREATE TRIGGER `${TABLE_NAME}$log$bu` BEFORE UPDATE ON `${TABLE_NAME}`
FOR EACH ROW BEGIN
  insert into `${TABLE_NAME}$log` select *, null, 1, now() from `${TABLE_NAME}`
  where id= OLD.id ;
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS `${TABLE_NAME}$log$bd`;
DELIMITER $$
CREATE TRIGGER `${TABLE_NAME}$log$bd` BEFORE DELETE ON `${TABLE_NAME}`
FOR EACH ROW BEGIN
  insert into `${TABLE_NAME}$log` select *, null, 2, now() from `${TABLE_NAME}`
  where id= OLD.id ;
END$$
DELIMITER ;
'''

[datasource]
# 数据源名字和信息（和驱动有关）
prd_main = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/godbart_prd_main'
prd_2018 = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/godbart_prd_2018'
dev_main = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/godbart_dev_main'
lcl_main = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/godbart_lcl_main'
lcl_test = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/test'
