[preference]
# 数据库类型，目前只支持mysql
databasetype = 'mysql'
# 默认分割法
delimiterraw = ';'
# 重定义分隔符
delimitercmd = 'DELIMITER'

# 单多行注释，正则处理，不做语法分析
linecomment = '--'
multcomment = ['/*','*/']

# 日期格式化
fmtdatetime='2006-01-02 15:04:05.000'

# 连接池有关的，sql.DB一致
connmaxopen = 10
connmaxidel = 2

[datasource]
# 数据源名字和信息（和驱动有关）
prd_main = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/godbart_prd_main'
prd_2018 = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/godbart_prd_2018'
dev_main = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/godbart_dev_main'
lcl_main = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/godbart_lcl_main'
lcl_test = 'trydofor:moilioncircle@tcp(127.0.0.1:3306)/test'
